/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cubrid_validator_SQLValidator */

#ifndef _Included_org_cubrid_validator_SQLValidator
#define _Included_org_cubrid_validator_SQLValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cubrid_validator_SQLValidator
 * Method:    validateSQL
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cubrid_validator_SQLValidator_validateSQL
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
